<?php

namespace Pages\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
    public function findByDeleted() {
        $gb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.deletedAt IS NOT NULL');
        
        return $gb->getQuery()->getResult();
    }
}
